// Generated by Xata Codegen 0.25.2. Please do not edit.
import { buildClient } from '@xata.io/client';
/** @typedef { import('./types').SchemaTables } SchemaTables */
/** @type { SchemaTables } */
const tables = [
	{
		name: 'event',
		columns: [
			{ name: 'course', type: 'link', link: { table: 'course' } },
			{ name: 'host', type: 'link', link: { table: 'host' } },
			{ name: 'classroom', type: 'link', link: { table: 'classroom' } },
			{ name: 'name', type: 'string' },
			{ name: 'start', type: 'datetime' },
			{ name: 'end', type: 'datetime' }
		]
	},
	{
		name: 'classroom',
		columns: [
			{ name: 'max', type: 'int', notNull: true, defaultValue: '0' },
			{ name: 'name', type: 'string', unique: true },
			{ name: 'code', type: 'int', unique: true }
		],
		revLinks: [{ column: 'classroom', table: 'event' }]
	},
	{
		name: 'host',
		columns: [{ name: 'name', type: 'string', unique: true }],
		revLinks: [{ column: 'host', table: 'event' }]
	},
	{
		name: 'course',
		columns: [
			{ name: 'name', type: 'string', defaultValue: 'error' },
			{ name: 'code', type: 'string', unique: true }
		],
		revLinks: [{ column: 'course', table: 'event' }]
	}
];
/** @type { import('@xata.io/client').ClientConstructor<{}> } */
const DatabaseClient = buildClient();
const defaultOptions = {
	databaseURL: 'https://utec-classrooms-rmhlob.us-east-1.xata.sh/db/utec-classrooms'
};
/** @typedef { import('./types').DatabaseSchema } DatabaseSchema */
/** @extends DatabaseClient<DatabaseSchema> */
export class XataClient extends DatabaseClient {
	constructor(options = {}) {
		super({ ...defaultOptions, ...options }, tables);
	}
}

import { XATA_API_KEY } from '$env/static/private';

/** @type { XataClient | undefined } */
let instance = undefined;
/** @type { () => XataClient } */
export const getXataClient = () => {
	if (instance) return instance;
	instance = new XataClient({
		apiKey: XATA_API_KEY
	});
	return instance;
};
